---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/segmentio/golines
    rev: v0.11.0
    hooks:
      - id: golines

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
